### ISSUE TITLE
upload_mask

### ISSUE THREAD

**Issue by Dream12211314** [BerivanIsik/sparse-random-networks#3]
Why use  "updates_s = np.where(updates_s == 0, self.epsilon, updates_s) " and "updates_s = np.where(updates_s == 1, 1-self.epsilon, updates_s)"? 
It may be not binary mask upload from client to server ,which causes the same communication cost as standard FL

**Comment by BerivanIsik** [comment]
Thank you for the question! We introduced this small value, `self.epsilon`, to avoid numerical errors when the server takes the inverse sigmoid of the aggregated masks. For instance, if all clients communicate 1 for a coordinate, then the aggregate would also be 1, but the inverse sigmoid is not defined for 1. In practice, the clients would not add `self.epsilon` themselves; instead, they would still communicate a binary mask (i.e., 0 or 1) and the server would introduce `self.epsilon` if necessary. So, the clients would still communicate a binary mask with a significantly lower cost than standard FL. 

Please let us know if there is any remaining confusion.
